<?= Form::open(); ?>

<div class="row">
    <div class="col-5">
        <?= Form::label('Nombre(s)', 'customer_first_name', ["class" => "form-label"]) ?>
        <?= Form::text('customer.first_name', $attrs = ["class" => "form-control"]) ?>
    </div>
    <div class="col-5">
        <?= Form::label('Apellido(s)', 'customer_last_name', ["class" => "form-label"]) ?>
        <?= Form::text('customer.last_name', $attrs = ["class" => "form-control"]) ?>
    </div>
</div>
<div class="row">
    <div class="col-5">
        <?= Form::label('Email', 'customer_email', ["class" => "form-label"]) ?>
        <?= Form::email('customer.email', $attrs = ["class" => "form-control"]) ?>
    </div>
    <div class="col-5">
        <?= Form::label('Contraseña', 'customer_password', ["class" => "form-label"]) ?>
        <input id="customer_password" name="customer[password]" type="password"
               class="form-control" />
    </div>
</div>
<div class="row">
    <div class="col-5">
        <?= Form::label('Tienda', 'customer_store_id', ["class" => "form-label"]) ?>
        <?= Form::dbSelect($itemId = 'customer.store_id', $show = 'nombre', $data = ['Store', 'find'],
            $blank = 'Seleccione una tienda',
            $attrs = ["class" => "form-control js-example-basic-single"],
            $value = $customer->store_id)
        ?>
    </div>
</div>

<br>
<?php View::partial('address/form2',null,['address'=>$address]) ?>

<?= Form::submit('Guardar', $attrs = ["class" => "mt-5 btn btn-primary"]) ?>

<?= Form::close() ?>