<?php View::content(); ?>
<div class="hero">
    <h3 class="linea-azul">Recomendaciones</h3>
</div>

<?php View::partial('index/carousel',null,['films' => $randomFilms]);
View::partial('index/cards',null, ['titulo'=>'Latest films','films' => $newestFilms]); ?>
<div class="mb-5"></div>
<?php View::partial('index/cards',null, ['titulo'=>'Most popular','films' => $popularFilms]); ?>
<div class="mb-5"></div>
<?php foreach ($randomCategories as $i => $c):
    View::partial('index/cards',null,
        ['titulo'=>$c->name,'films' => $randomFilmsByCategory[$i]]); ?>
    <div class="mt-1 mb-5">
        <a href="/chadfilms/genres/show/<?= $c->id ?>" class="btn btn-primary">
            Más de <?= $c->name ?>
        </a>
    </div>
<?php endforeach; ?>

<a href="/chadfilms/genres/" class="btn btn-dark">Más géneros</a>
