<h1><?= $subtitle ?></h1>

<a href="#" class="btn btn-danger btn-sm">Agregar</a>



<table border="1">
    <thead>
    <tr>
        <th>Id</th>
        <th>No control</th>
        <th>Nombre</th>
        <th>Carrera</th>
        <th>Semestre</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </tbody>
</table>