<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>KumbiaPHP Framework</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="/KumbiaPHP/libs/bootstrap-5.3.2-dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen" />
 </head>
</head>
<body>
<div class="container">
  <header class="row">
      <div class="col-8">
          <?= Html::link('', Html::img('kumbiaphp.svg', 'KumbiaPHP logo'), 'title="Inicio"') ?>
      </div>
      <div class="col-4 text-right">
          App: <strong><?= basename(dirname(APP_PATH)) ?></strong> (<?= PRODUCTION ? 'Production' : 'Development' ?>)
      </div>
  </header>
  <?php View::content() ?>
  <?php View::partial('kumbia/footer') ?>
</div>
</body>
</html>
