<li class="dropdown pc-h-item">
    <a
        class="pc-head-link arrow-none me-0"
        href="/chadfilms/customer/checkout"
        aria-haspopup="false"
        aria-expanded="false"
    >
        <i data-feather="shopping-cart"></i>
        <?php if ($numberItemsOnCart !== 0): ?>
            <span class="badge bg-success pc-h-badge"><?= $numberItemsOnCart ?></span>
        <?php endif; ?>
    </a>
    <!-- Quizás se pueda utilizar como vista previa del carro
    <div class="dropdown-menu dropdown-notification dropdown-menu-end pc-h-dropdown">
        <div class="dropdown-header d-flex align-items-center justify-content-between">
            <h5 class="m-0">Notifications</h5>
            <a href="#!" class="btn btn-link btn-sm">Mark all read</a>
        </div>
        <div class="dropdown-body text-wrap header-notification-scroll position-relative" style="max-height: calc(100vh - 215px)">
            <p class="text-span">Today</p>
            <div class="card mb-0">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="flex-shrink-0">
                            <img class="img-radius avtar rounded-0" src="/chadfilms/libs/datta-able/dist/assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <span class="float-end text-sm text-muted">2 min ago</span>
                            <h5 class="text-body mb-2">UI/UX Design</h5>
                            <p class="mb-0"
                            >Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of
                                type and scrambled it to make a type</p
                            >
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-0">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="flex-shrink-0">
                            <img class="img-radius avtar rounded-0" src="/chadfilms/libs/datta-able/dist/assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <span class="float-end text-sm text-muted">1 hour ago</span>
                            <h5 class="text-body mb-2">Message</h5>
                            <p class="mb-0">Lorem Ipsum has been the industry's standard dummy text ever since the 1500.</p>
                        </div>
                    </div>
                </div>
            </div>
            <p class="text-span">Yesterday</p>
            <div class="card mb-0">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="flex-shrink-0">
                            <img class="img-radius avtar rounded-0" src="/chadfilms/libs/datta-able/dist/assets/images/user/avatar-3.jpg" alt="Generic placeholder image">
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <span class="float-end text-sm text-muted">2 hour ago</span>
                            <h5 class="text-body mb-2">Forms</h5>
                            <p class="mb-0"
                            >Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of
                                type and scrambled it to make a type</p
                            >
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-0">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="flex-shrink-0">
                            <img class="img-radius avtar rounded-0" src="/chadfilms/libs/datta-able/dist/assets/images/user/avatar-4.jpg" alt="Generic placeholder image">
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <span class="float-end text-sm text-muted">12 hour ago</span>
                            <h5 class="text-body mb-2">Challenge invitation</h5>
                            <p class="mb-2"><span class="text-dark">Jonny aber</span> invites to join the challenge</p>
                            <button class="btn btn-sm btn-outline-secondary me-2">Decline</button>
                            <button class="btn btn-sm btn-primary">Accept</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-0">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="flex-shrink-0">
                            <img class="img-radius avtar rounded-0" src="/chadfilms/libs/datta-able/dist/assets/images/user/avatar-5.jpg" alt="Generic placeholder image">
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <span class="float-end text-sm text-muted">5 hour ago</span>
                            <h5 class="text-body mb-2">Security</h5>
                            <p class="mb-0"
                            >Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of
                                type and scrambled it to make a type</p
                            >
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center py-2">
            <a href="#!" class="link-danger">Clear all Notifications</a>
        </div>
    </div>
    -->
</li>