<li class="dropdown pc-h-item">
    <a
        class="pc-head-link dropdown-toggle arrow-none m-0 trig-drp-search"
        data-bs-toggle="dropdown"
        href="#"
        role="button"
        aria-haspopup="false"
        aria-expanded="false"
    >
        <i data-feather="search"></i>
    </a>
    <div class="dropdown-menu pc-h-dropdown drp-search">
        <form class="px-3 py-2">
            <input type="search" class="form-control border-0 shadow-none" placeholder="Search here. . ." />
        </form>
    </div>
</li>