<div class="navbar-content">
    <ul class="pc-navbar">
        <li class="pc-item pc-caption">
            <label>Navigation</label>
        </li>

        <li class="pc-item">
            <a href="/chadfilms/genres" class="pc-link">
            <span class="pc-micon">
              <i data-feather="hash"></i>
            </span>
                <span class="pc-mtext">Genres</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/customer/purchases" class="pc-link">
            <span class="pc-micon">
              <i data-feather="pocket"></i>
            </span>
                <span class="pc-mtext">Purchases</span>
            </a>
        </li>

        <li class="pc-item pc-caption">
            <label>Prácticas (Sección de administrador)</label>
            <i data-feather="sidebar"></i>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/category" class="pc-link">
            <span class="pc-micon">
              <i data-feather="hash"></i>
            </span>
                <span class="pc-mtext">Category</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/city" class="pc-link">
            <span class="pc-micon">
              <i data-feather="square"></i>
            </span>
                <span class="pc-mtext">City</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/country" class="pc-link">
            <span class="pc-micon">
              <i data-feather="flag"></i>
            </span>
                <span class="pc-mtext">Country</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/customer" class="pc-link">
            <span class="pc-micon">
              <i data-feather="user"></i>
            </span>
                <span class="pc-mtext">Costumer</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/film" class="pc-link">
            <span class="pc-micon">
              <i data-feather="film"></i>
            </span>
                <span class="pc-mtext">Film</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/language" class="pc-link">
            <span class="pc-micon">
              <i data-feather="bell"></i>
            </span>
                <span class="pc-mtext">Language</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/staff" class="pc-link">
            <span class="pc-micon">
              <i data-feather="briefcase"></i>
            </span>
                <span class="pc-mtext">Staff</span>
            </a>
        </li>
        <li class="pc-item">
            <a href="/chadfilms/store" class="pc-link">
            <span class="pc-micon">
              <i data-feather="shopping-bag"></i>
            </span>
                <span class="pc-mtext">Store</span>
            </a>
        </li>

<!--        <li class="pc-item pc-caption">
            <label>Other</label>
            <i data-feather="sidebar"></i>
        </li>
        <li class="pc-item">
            <a href="../dashboard/index.html" class="pc-link">
            <span class="pc-micon">
              <i data-feather="home"></i>
            </span>
                <span class="pc-mtext">Dashboard</span>
            </a>
        </li>
        <li class="pc-item pc-hasmenu">
            <a href="#!" class="pc-link">
            <span class="pc-micon">
              <i data-feather="align-right"></i>
            </span>
                <span class="pc-mtext">Menu levels</span><span class="pc-arrow"><i class="ti ti-chevron-right"></i></span>
            </a>
            <ul class="pc-submenu">
                <li class="pc-item"><a class="pc-link" href="#!">Level 2.1</a></li>
                <li class="pc-item pc-hasmenu">
                    <a href="#!" class="pc-link"
                    >Level 2.2<span class="pc-arrow"><i class="ti ti-chevron-right"></i></span
                        ></a>
                    <ul class="pc-submenu">
                        <li class="pc-item"><a class="pc-link" href="#!">Level 3.1</a></li>
                        <li class="pc-item"><a class="pc-link" href="#!">Level 3.2</a></li>
                        <li class="pc-item pc-hasmenu">
                            <a href="#!" class="pc-link"
                            >Level 3.3<span class="pc-arrow"><i class="ti ti-chevron-right"></i></span
                                ></a>
                            <ul class="pc-submenu">
                                <li class="pc-item"><a class="pc-link" href="#!">Level 4.1</a></li>
                                <li class="pc-item"><a class="pc-link" href="#!">Level 4.2</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="pc-item pc-hasmenu">
                    <a href="#!" class="pc-link"
                    >Level 2.3<span class="pc-arrow"><i class="ti ti-chevron-right"></i></span
                        ></a>
                    <ul class="pc-submenu">
                        <li class="pc-item"><a class="pc-link" href="#!">Level 3.1</a></li>
                        <li class="pc-item"><a class="pc-link" href="#!">Level 3.2</a></li>
                        <li class="pc-item pc-hasmenu">
                            <a href="#!" class="pc-link">
                                Level 3.3
                                <span class="pc-arrow"><i class="ti ti-chevron-right"></i></span>
                            </a>
                            <ul class="pc-submenu">
                                <li class="pc-item"><a class="pc-link" href="#!">Level 4.1</a></li>
                                <li class="pc-item"><a class="pc-link" href="#!">Level 4.2</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li class="pc-item">
            <a href="../other/sample-page.html" class="pc-link">
                <span class="pc-micon"><i data-feather="sidebar"></i></span>
                <span class="pc-mtext">Sample page</span>
            </a>
        </li> -->
    </ul>
</div>