<nav class="pc-sidebar">
    <div class="navbar-wrapper">
        <div class="m-header">
            <a href="/chadfilms" class="b-brand text-primary">
                <!-- ========   Change your logo from here   ============ -->
                <img src="/chadfilms/img/chad.png" height="50px" class="epic" alt="logo">
                <h4 class="epic-name">ChadFilms</h4>
            </a>
        </div>
        <?php View::partial("datta_able/sidebar_content"); ?>
    </div>
</nav>