<?php View::content() ?>

<iframe class="video-iframe" width="100%" src="https://www.youtube.com/embed/<?= $film->video_id ?>"
        title="<?= $film->title ?>" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope;
            picture-in-picture; web-share"
        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
</iframe>

<h3 class="linea-azul mt-5">Leave a comment</h3>

<?= Form::open(); ?>

<?= Form::textarea('film_comments.comment',
    $attrs=["class"=>"form-control","placeholder"=>"Comment","rows"=>"5"]) ?>

<?= Form::submit('Post comment', $attrs=["class"=>"mt-3 btn btn-primary"]) ?>

<?= Form::close() ?>

<?php if ($filmSavedComments): ?>
        <h3 class="linea-azul mt-5">All comments</h3>
<?php
        foreach ($filmSavedComments as $fc):
        View::partial('index/card_comment',null,
            ['user'=>$fc->getCustomer()->first_name. ' ' . $fc->getCustomer()->last_name,
                'time'=>$fc->getTime(),
                'comment'=>$fc->comment]
        );
        endforeach;
    endif; ?>


